### ISSUE TITLE
App Structure

### ISSUE THREAD

**Issue by mattfaluotico** [MattFaluotico/InformationSecurityAndroid#1]

**Comment by mattfaluotico** [comment]
@trong-le or @milltorr can you help with this?

**Comment by milltorr** [comment]
Hey everybody I found a site that had some free crime APIs that you might want to check out. https://www.mashape.com/explore?query=Crime
Let me know if you think any of these will work.  Thanks everybody.

**Comment by user1m** [comment]
So those api's unfortunately won't work.
1. CrimeScore: " CrimeScores are returned for the following cities, with more being added soon. San Francisco, CA Washington, DC Anchorage, AK Louisville, KY Miami, FL Fort Worth, TX Chicago, IL Seattle, WA Indianapolis, IN Albuquerque, NM Richmond, VA Cincinnati, OH Atlanta, GA CrimeScore rating is a propriety methodology based on address-level crime reports.."
2. CrimeData: has no data for Columbus' long+lat (39.9929821 N , 83.00122099999999 W)
3. Gotta pay
4. is really #1

But I found an api that will work...but looks like a small independent project where you gotta request api access which I've done: http://spotcrime.com/#43201

**Comment by user1m** [comment]
There's also this: http://www.columbuspolice.org/Reports/
But it's only columbus specific

**Comment by user1m** [comment]
So the SpotCrime api apparently isn't public:

On Fri, Apr 10, 2015 at 12:06 AM, Feedly Backster feedback@spotcrime.com wrote:
No, I'm sorry, we don't offer a public API.

Thank you,
Michelle

On Thu, Apr 9, 2015 at 10:15 PM, mbembac@gmail.com wrote:
Reportsee.com feedback submitted
 at spotcrime.com
 on Thu, 09 Apr 2015 22:15:52 -0400
 from google-proxy-64-233-172-230.google.com (64.233.172.230)

---

Action: Feedback
Name: Claudius
Email: mbembac@gmail.com

---

Hi I'm emailing to see if I could get api key access. I would like to use the spotcrime api for a class final project due in 2 weeks, so would greatly appreciate a quick response.

Thanks!

**Comment by user1m** [comment]
We need to find an open (ideally free) crime api

**Comment by mattfaluotico** [comment]
Just found this. We could use the CSV and return JSON for a specific city.

**Comment by user1m** [comment]
Matt there's no link

**Comment by mattfaluotico** [comment]
Oops.... I'll add it in a minute. 

It's no for Ohio. We may need to do this for w city like Seattle. 

-mf

**Comment by derektesh** [comment]
I don't think doing a city that is not Columbus is a big deal. As long as the application works, we can say that it works in the cities we have data for and will work in other cities in the future once the data is available.

---

Derek Esh
The Ohio State University
Computer Science and Engineering- 2015
Sigma Pi Fraternity, International
New Member Educator

Cell: (740) 364-8293
E-mail: esh.6@osu.edu
